name: dcdg
description: A tool to automatically generate class diagrams (like UML) from a Dart package.
version: 4.1.0
homepage: https://github.com/glesica/dcdg.dart
executables:
  dcdg:

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  analyzer:
    git:
      url: https://github.com/arrrtem22/sdk.git
      path: pkg/analyzer
  args: ^2.0.0
  path: ^1.4.0

dev_dependencies:
  lints:
  test:

